#!/bin/bash

add_gits_cmd () {
	echo "#!/bin/bash" > gits
	echo "../../gits \"\$@\"" >> gits
	chmod 755 gits
}

# this creates a git repository the normal way
# setups up gits with it, then runs gits init for a second
test1 () {
	mkdir test1
	cd test1
	echo "# repo1 has .gitignore and README" > file.txt
	echo "# repo1" > .gitignore
	echo "# repo1" > README.md
	git init
	git add .
	git commit -m "commit for repo1"
	add_gits_cmd
	./gits setup repo1
	./gits init repo2
}
test2 () {
	mkdir "$1"
	cd "$1"
	echo "# $2 has only this file" > file.txt
	git init
	git add .
	git commit -m "commit for $2"
	add_gits_cmd
	./gits setup full1
	./gits init "from gits init"
}

"$1"
